### PR TITLE
HRSL vector v1

### LINKED ISSUE #2: Develop a tasking manager prioritization framework using FB's High Resolution Settlement Layer to identify areas to map missing roads
see [prior art](https://www.openstreetmap.org/user/maning/diary/371456)
Basic steps are:

1. Convert HRSL to vector
2. Add a buffer (~100-200 m) to cover areas that are adjacent to settlements
3. Intersect the buffer output to admin boundaries (so we can filter by admin jurisdiction later)

### PR DESCRIPTION
**Pull request by maning**
Resolves https://github.com/OSMPH/Tabang-AI/issues/2

This PR add the HRSL derived vector for prioritizing mapping project with AI.  The data has the following files:

* data/README.md
* data/hrsl_ph_500m_grid_v1.geojson.zip
* data/hrsl_ph_buffer100m_v1.geojson.zip
* data/ph_admin_code.csv

Description of each file is in the README.md

ph_hrsl_v1

@seav @govvin Can one of you download and inspect the data locally before I merge?  🙇‍♀

### CODE REVIEW

**Comment by seav** [comment]
Some comments:
- The coordinates of the GeoJSON have 9 decimal places. This is too much precision. 5 should be enough.
- The GeoJSON file contains 1600+ `MultiPolygon` features with complex shapes. This is very slow to load in tools/applications such as QGIS. Maybe it would be better to split the GeoJSON into smaller pieces, maybe grouped by `ADM2` (province) level.

**Comment by seav** [comment]
Nice to have: If the `MultiPolygon` inner rings have a small area (FSVO small), it might be better to just remove them to simplify the shapes further.

**Comment by govvin** [comment]
Thank you, @maning .

Please consider the following:

image
* can we improve optimize the file size further by simplifying vertices

image
the polygon features look ideal for settlements, but we could be missing out on roads that connect these settlements when use this to create tasks (lines in red simulate roads not within feature outlines)

* we probably should merge polygons within 150m of other polygons.
* How can we better handle polygon islands within polygons?
* could we be splitting the features with adm3 intersections prematurely?

**Comment by govvin** [comment]
Before we publish a version of this, how about we run a test over the same area covered by Ompong last year and compare all features added within the period (Sep-Oct) the task was running and compare that coverage against this one?

**Comment by maning** [comment]
I updated the data, see OP

Changes includes the following based on your comment:

> The coordinates of the GeoJSON have 9 decimal places. This is too much precision. 5 should be enough.

👍 geojson is now 5 precision.

> The GeoJSON file contains 1600+ MultiPolygon features with complex shapes. This is very slow to load in tools/applications such as QGIS. Maybe it would be better to split the GeoJSON into smaller pieces, maybe grouped by ADM2 (province) level.

👍 I converted to single-parts but it still one big geojson.  Its much faster to load now than before.
Also to reduce file size, I removed the Pcode attribute and added a separate csv file. User can join this attributes if they need it for analysis.

> can we improve optimize the file size further by simplifying vertices

👍 I simplified the hrsl_ph_buffer100m_v1 by removing vertices within 10m.

> the polygon features look ideal for settlements, but we could be missing out on roads that connect these settlements when use this to create tasks (lines in red simulate roads not within feature outlines)

👍 To resolve this, I created a new geojson with 500m grid (`hrsl_ph_500m_grid_v1`) intersected from the `hrsl_ph_buffer100m_v1` this should cover most cases.  I also think this is ideal vector we can use fro preparing the tasks.

 > Before we publish a version of this, how about we run a test over the same area covered by Ompong last year and compare all features added within the period (Sep-Oct) the task was running and compare that coverage against this one?

👍 Yes, I did a quick evaluation see next comment.
👎 Not in Ompong area though. :)

**Comment by maning** [comment]
To quickly evaluate if the derived vectors will cover most settlement areas in a certain area.  I compared the vector data and OSM coverage in Banton Island.  I chose Banton Island because I used the island to test if HRSL is an appropriate data to use for prioritizing remote mapping (see my [OSM diary](https://www.openstreetmap.org/user/maning/diary/371456)).

### Details of the comparison.

The OSM features were counted if it is partially within each polygon.

| | hrsl_ph_buffer100m_v1 | hrsl_ph_500m_grid_v1
|---|---|---|
Map |hrsl | grid
|Building | - within polygon - 1486 <br> - outside polygon - 376 | - within polygon - 1746 <br> - outside polygon - 116 |
|Roads | - within polygon - 85 <br> - outside polygon - 10 | - within polygon - 91 <br> - outside polygon - 4
"Detection rate" (in %) | - Building - 79.8 <br> - Road - 89.4 | - Building - **93.3** <br> - Road - **95.8**

### Summary

* `hrsl_ph_buffer100m_v1` covers a much less area than `hrsl_ph_500m_grid_v1` .  This means there is less area to map.  In addition, `hrsl_ph_500m_grid_v1`  can have some areas that don't have any features to map for example, if the grid is between land and sea.
* Both polygon was able to detect most buildings and roads (79-95%), but `hrsl_ph_500m_grid_v1` has the highest detection rate.
* **Using this data for mapping roads and buildings does not guarantee 100% coverage but good enough for remote mapping.**  *I talked about this in detail in the diary.*

**Comment by maning** [comment]
@govvin @seav Please give this a review again.  Thanks!

**Comment by govvin** [comment]
Let's  specifiy the license to the data. Also, double-check on the license of the HRSL dataset.

It is vry challenging to achieve 100% coverage within the context of emergency mapping, and there's always the risk of not mapping isolated settlements - and even with the current approach there's no assurance of that.  Helping contributors focus on smaller areas are extremely helpful. Emergency response resources are limited, and DRR managers will often focus initially on where impact is greatest.

Once released, it might be a good idea to conduct a public workshop (e.g. potential TM project managers, DRR people, etc) and record it on video.

**Comment by maning** [comment]
> Let's specifiy the license to the data. Also, double-check on the license of the HRSL dataset.

Good point! HSRL is CC-By 4.0 while ph admin boundaries are "Humanitarian use only"
What's the appropriate license for derived data coming from these two?

@seav

**Comment by maning** [comment]
> Let's specifiy the license to the data. Also, double-check on the license of the HRSL dataset.

Let's resolve this issue with a project wide license, tracking here: https://github.com/OSMPH/Tabang-AI/issues/8

**Review by govvin — APPROVED** [review]
Looks good, and all the inputs from the test version has been incorporated.

**Pull request merged**
